openapi: 3.1.0
info:
  contact:
    email: philipp.schmurr@kit.edu
  description: "This is a Schema extraction API based on the OpenAPI 3.1 specification.\
    \  You can find out more about\nSwagger at [https://swagger.io](https://swagger.io). "
  license:
    name: MIT
  termsOfService: http://swagger.io/terms/
  title: Schema API - OpenAPI 3.1
  version: 0.7.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
- url: http://localhost:7373
tags:
- description: Everything about your existing data's schema
  externalDocs:
    description: Find out more
    url: http://swagger.io
  name: schema
- description: Access to information on the schema of individual entities
  externalDocs:
    description: Find out more about our store
    url: http://swagger.io
  name: entity
- description: Operations about keys
  name: key
- description: A file format supported by the schema API
  name: format
paths:
  /data-sources:
    get:
      description: desc
      operationId: getAllDataSourceMeta
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/DataSource'
                type: array
            application/x-yaml:
              schema:
                items:
                  $ref: '#/components/schemas/DataSource'
                type: array
            application/xml:
              schema:
                items:
                  $ref: '#/components/schemas/DataSource'
                type: array
                xml:
                  name: data-sources
          description: successful operation
      summary: Get meta information about all registered data sources
      tags:
      - data-source
    post:
      description: desc
      operationId: addDataSourceMeta
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DataSource'
          application/x-yaml:
            schema:
              $ref: '#/components/schemas/DataSource'
          application/xml:
            schema:
              $ref: '#/components/schemas/DataSource'
        description: specification of data source meta record
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataSource'
            application/x-yaml:
              schema:
                $ref: '#/components/schemas/DataSource'
            application/xml:
              schema:
                $ref: '#/components/schemas/DataSource'
          description: successful operation
        "400":
          description: Bad request
      summary: Insert a new data source meta record
      tags:
      - data-source
  /data-sources/{dataSourceId}:
    get:
      description: desc
      operationId: getDataSourceMeta
      parameters:
      - $ref: '#/components/parameters/dataSourceId'
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/DataSource'
                type: array
            application/x-yaml:
              schema:
                items:
                  $ref: '#/components/schemas/DataSource'
                type: array
            application/xml:
              schema:
                items:
                  $ref: '#/components/schemas/DataSource'
                type: array
                xml:
                  name: data-sources
          description: successful operation
      summary: Get meta information about a specified data sources
      tags:
      - data-source
  /data-sources/{dataSourceId}/{pluginInputField}:
    get:
      description: desc
      operationId: getDataSourceContent
      parameters:
      - $ref: '#/components/parameters/dataSourceId'
      - $ref: '#/components/parameters/pluginInputField'
      responses:
        "200":
          content:
            application/octet-stream:
              schema:
                format: binary
                type: string
          description: successful operation
      summary: Get content of a specified data sources
      tags:
      - data-source
    post:
      description: desc
      operationId: uploadDataSourceContent
      parameters:
      - $ref: '#/components/parameters/dataSourceId'
      - $ref: '#/components/parameters/pluginInputField'
      responses:
        "200":
          description: successful operation
      summary: Upload the content of a specified data source
      tags:
      - data-source
  /formats:
    get:
      description: desc
      operationId: getAllFormats
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Format'
                type: array
            application/x-yaml:
              schema:
                items:
                  $ref: '#/components/schemas/Format'
                type: array
            application/xml:
              schema:
                items:
                  $ref: '#/components/schemas/Format'
                type: array
                xml:
                  name: formats
          description: successful operation
      summary: Get all supported formats of this API
      tags:
      - format
  /schemata:
    get:
      description: desc
      operationId: getAllSchemas
      parameters:
      - $ref: '#/components/parameters/preventOptimization'
      - $ref: '#/components/parameters/preventAutomaticOptimization'
      - $ref: '#/components/parameters/preventUserOptimization'
      - $ref: '#/components/parameters/generateInverseRelations'
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Schema'
                type: array
            application/xml:
              schema:
                items:
                  $ref: '#/components/schemas/Schema'
                type: array
                xml:
                  name: schemas
            application/x-yaml:
              schema:
                items:
                  $ref: '#/components/schemas/Schema'
                type: array
          description: successful operation
      summary: Get all available schemas from this API server
      tags:
      - schema
  /schemata/{schemaId}:
    get:
      description: desc
      operationId: getSchemaByID
      parameters:
      - $ref: '#/components/parameters/schemaId'
      - $ref: '#/components/parameters/preventOptimization'
      - $ref: '#/components/parameters/preventAutomaticOptimization'
      - $ref: '#/components/parameters/preventUserOptimization'
      - $ref: '#/components/parameters/generateInverseRelations'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Schema'
            application/x-yaml:
              schema:
                $ref: '#/components/schemas/Schema'
            application/xml:
              schema:
                $ref: '#/components/schemas/Schema'
          description: successful operation
        "404":
          description: not found
      summary: Get schema by ID
      tags:
      - schema
  /schemata/{schemaId}/corrections/entities:
    post:
      description: Add an entirely new entity
      operationId: addNewEntityCorrection
      parameters:
      - $ref: '#/components/parameters/schemaId'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Entity'
          application/x-yaml:
            schema:
              $ref: '#/components/schemas/Entity'
          application-xml:
            schema:
              $ref: '#/components/schemas/Entity'
        description: A new entity object
        required: true
      responses:
        "200":
          description: successful operation
        "400":
          content:
            text/plain:
              schema:
                type: string
          description: bad request
        "404":
          description: schema not found
      summary: Add an entirely new entity
      tags:
      - correction
  /schemata/{schemaId}/corrections/entities/{entityId}:
    post:
      description: change entity name
      operationId: changeEntityNameCorrection
      parameters:
      - $ref: '#/components/parameters/schemaId'
      - $ref: '#/components/parameters/entityId'
      requestBody:
        content:
          text/plain:
            schema:
              type: string
        description: new name as plain string
        required: true
      responses:
        "200":
          description: successful operation
        "400":
          content:
            text/plain:
              schema:
                type: string
          description: bad request
        "404":
          description: schema or entity not found
      summary: change entity name
      tags:
      - correction
  /schemata/{schemaId}/corrections/entities/{entityId}/modifiers:
    put:
      description: Update entity modifiers
      operationId: updateEntityModifiersCorrection
      parameters:
      - $ref: '#/components/parameters/schemaId'
      - $ref: '#/components/parameters/entityId'
      requestBody:
        content:
          application/json:
            schema:
              items:
                $ref: '#/components/schemas/EntityModifier'
              type: array
          application/x-yaml:
            schema:
              items:
                $ref: '#/components/schemas/EntityModifier'
              type: array
          application-xml:
            schema:
              items:
                $ref: '#/components/schemas/EntityModifier'
              type: array
              xml:
                name: EntityModifiers
        description: list of EntityModifier objects
        required: true
      responses:
        "200":
          description: successful operation
        "400":
          content:
            text/plain:
              schema:
                type: string
          description: bad request
        "404":
          description: schema or entity not found
      summary: Update entity modifiers
      tags:
      - correction
  /schemata/{schemaId}/corrections/entities/{entityId}/attributes:
    post:
      description: Add an entirely new attribute
      operationId: addNewAttributeCorrection
      parameters:
      - $ref: '#/components/parameters/schemaId'
      - $ref: '#/components/parameters/entityId'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Attribute'
          application/x-yaml:
            schema:
              $ref: '#/components/schemas/Attribute'
          application-xml:
            schema:
              $ref: '#/components/schemas/Attribute'
        description: A new attribute object
        required: true
      responses:
        "200":
          description: successful operation
        "400":
          content:
            text/plain:
              schema:
                type: string
          description: bad request
        "404":
          description: schema or entity not found
      summary: Add an entirely new attribute
      tags:
      - correction
  /schemata/{schemaId}/corrections/entities/{entityId}/attributes/{attributeId}:
    post:
      description: change attribute name
      operationId: changeAttributeNameCorrection
      parameters:
      - $ref: '#/components/parameters/schemaId'
      - $ref: '#/components/parameters/entityId'
      - $ref: '#/components/parameters/attributeId'
      requestBody:
        content:
          text/plain:
            schema:
              type: string
        description: new name as plain string
        required: true
      responses:
        "200":
          description: successful operation
        "400":
          content:
            text/plain:
              schema:
                type: string
          description: bad request
        "404":
          description: "schema, entity or attribute not found"
      summary: change attribute name
      tags:
      - correction
  /schemata/{schemaId}/corrections/entities/{entityId}/attributes/{attributeId}/modifiers:
    put:
      description: Update attribute modifiers
      operationId: updateAttributeModifiersCorrection
      parameters:
      - $ref: '#/components/parameters/schemaId'
      - $ref: '#/components/parameters/entityId'
      - $ref: '#/components/parameters/attributeId'
      requestBody:
        content:
          application/json:
            schema:
              items:
                $ref: '#/components/schemas/AttributeModifier'
              type: array
          application/x-yaml:
            schema:
              items:
                $ref: '#/components/schemas/AttributeModifier'
              type: array
          application-xml:
            schema:
              items:
                $ref: '#/components/schemas/AttributeModifier'
              type: array
              xml:
                name: AttributeModifiers
        description: list of AttributeModifier objects
        required: true
      responses:
        "200":
          description: successful operation
        "400":
          content:
            text/plain:
              schema:
                type: string
          description: bad request
        "404":
          description: "schema, entity or attribute not found"
      summary: Update attribute modifiers
      tags:
      - correction
  /schemata/{schemaId}/corrections/entities/{entityId}/relations:
    post:
      description: Add an entirely new relation
      operationId: addNewRelationCorrection
      parameters:
      - $ref: '#/components/parameters/schemaId'
      - $ref: '#/components/parameters/entityId'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Relation'
          application/x-yaml:
            schema:
              $ref: '#/components/schemas/Relation'
          application-xml:
            schema:
              $ref: '#/components/schemas/Relation'
        description: A new relation object
        required: true
      responses:
        "200":
          description: successful operation
        "400":
          content:
            text/plain:
              schema:
                type: string
          description: bad request
        "404":
          description: schema or entity not found
      summary: Add an entirely new relation
      tags:
      - correction
  /schemata/{schemaId}/corrections/entities/{entityId}/relations/{relationId}:
    post:
      description: change relation name
      operationId: changeRelationNameCorrection
      parameters:
      - $ref: '#/components/parameters/schemaId'
      - $ref: '#/components/parameters/entityId'
      - $ref: '#/components/parameters/relationId'
      requestBody:
        content:
          text/plain:
            schema:
              type: string
        description: new name as plain string
        required: true
      responses:
        "200":
          description: successful operation
        "400":
          content:
            text/plain:
              schema:
                type: string
          description: bad request
        "404":
          description: "schema, entity or relation not found"
      summary: change relation name
      tags:
      - correction
  /schemata/{schemaId}/corrections/entities/{entityId}/relations/{relationId}/modifiers:
    put:
      description: Update relation modifiers
      operationId: updateRelationModifiersCorrection
      parameters:
      - $ref: '#/components/parameters/schemaId'
      - $ref: '#/components/parameters/entityId'
      - $ref: '#/components/parameters/relationId'
      requestBody:
        content:
          application/json:
            schema:
              items:
                $ref: '#/components/schemas/RelationModifier'
              type: array
          application/x-yaml:
            schema:
              items:
                $ref: '#/components/schemas/RelationModifier'
              type: array
          application-xml:
            schema:
              items:
                $ref: '#/components/schemas/RelationModifier'
              type: array
              xml:
                name: RelationModifiers
        description: list of RelationModifier objects
        required: true
      responses:
        "200":
          description: successful operation
        "400":
          content:
            text/plain:
              schema:
                type: string
          description: bad request
        "404":
          description: "schema, entity or relation not found"
      summary: Update relation modifiers
      tags:
      - correction
  /schemata/{schemaId}/diagram:
    get:
      description: desc
      operationId: getSchemaDiagram
      parameters:
      - $ref: '#/components/parameters/schemaId'
      - description: Toggle the rendering state of attributes
        explode: true
        in: query
        name: showAttributes
        required: false
        schema:
          default: true
          type: boolean
        style: form
      - description: Specify a list of highlighted entities
        explode: true
        in: query
        name: selectedEntities
        required: false
        schema:
          default: []
          items:
            type: string
          type: array
        style: form
      - description: The distance to render when using highlighted entities
        explode: true
        in: query
        name: renderDistance
        required: false
        schema:
          default: 2
          type: integer
        style: form
      - $ref: '#/components/parameters/preventOptimization'
      - $ref: '#/components/parameters/preventAutomaticOptimization'
      - $ref: '#/components/parameters/preventUserOptimization'
      - $ref: '#/components/parameters/generateInverseRelations'
      responses:
        "200":
          content:
            image/svg+xml:
              schema:
                type: string
            text/plain:
              schema:
                type: string
          description: successful operation
        "404":
          description: schema not found
      summary: Get a diagram for the schema
      tags:
      - schema
  /schemata/{schemaId}/partitioned-entities:
    get:
      description: desc
      operationId: getPartitionedEntitiesBySchema
      parameters:
      - $ref: '#/components/parameters/schemaId'
      - $ref: '#/components/parameters/preventOptimization'
      - $ref: '#/components/parameters/preventAutomaticOptimization'
      - $ref: '#/components/parameters/preventUserOptimization'
      - $ref: '#/components/parameters/generateInverseRelations'
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Partition'
                type: array
            application/x-yaml:
              schema:
                items:
                  $ref: '#/components/schemas/Partition'
                type: array
            application/xml:
              schema:
                items:
                  $ref: '#/components/schemas/Partition'
                type: array
                xml:
                  name: Partitions
          description: successful operation
      tags:
      - partition
  /schemata/{schemaId}/entities:
    get:
      description: desc
      operationId: getEntitiesBySchema
      parameters:
      - $ref: '#/components/parameters/schemaId'
      - $ref: '#/components/parameters/preventOptimization'
      - $ref: '#/components/parameters/preventAutomaticOptimization'
      - $ref: '#/components/parameters/preventUserOptimization'
      - $ref: '#/components/parameters/generateInverseRelations'
      - $ref: '#/components/parameters/entityFilter'
      - $ref: '#/components/parameters/entityFilterDistance'
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Entity'
                type: array
            application/xml:
              schema:
                items:
                  $ref: '#/components/schemas/Entity'
                type: array
                xml:
                  name: entities
            application/x-yaml:
              schema:
                items:
                  $ref: '#/components/schemas/Entity'
                type: array
          description: successful operation
      summary: Get all entities of a schema
      tags:
      - entity
  /schemata/{schemaId}/entities/{entityId}:
    get:
      description: desc
      operationId: getEntityById
      parameters:
      - $ref: '#/components/parameters/schemaId'
      - $ref: '#/components/parameters/entityId'
      - $ref: '#/components/parameters/preventOptimization'
      - $ref: '#/components/parameters/preventAutomaticOptimization'
      - $ref: '#/components/parameters/preventUserOptimization'
      - $ref: '#/components/parameters/generateInverseRelations'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Entity'
            application/xml:
              schema:
                $ref: '#/components/schemas/Entity'
            application/x-yaml:
              schema:
                $ref: '#/components/schemas/Entity'
          description: successful operation
      summary: Get a specific entity
      tags:
      - entity
components:
  parameters:
    dataSourceId:
      explode: false
      in: path
      name: dataSourceId
      required: true
      schema:
        type: string
      style: simple
    pluginInputField:
      explode: false
      in: path
      name: pluginInputField
      required: true
      schema:
        type: string
      style: simple
    EntityPrefix:
      explode: true
      in: query
      name: EntityPrefix
      required: false
      schema:
        default: ""
      style: form
    preventOptimization:
      explode: true
      in: query
      name: preventOptimization
      required: false
      schema:
        default: false
        type: boolean
      style: form
    preventAutomaticOptimization:
      explode: true
      in: query
      name: preventAutomaticOptimization
      required: false
      schema:
        default: false
        type: boolean
      style: form
    preventUserOptimization:
      explode: true
      in: query
      name: preventUserOptimization
      required: false
      schema:
        default: false
        type: boolean
      style: form
    generateInverseRelations:
      description: Toggles whether to generate inverse relations for each existing
        relation that has no schema based inverse
      explode: true
      in: query
      name: generateInverseRelations
      required: false
      schema:
        default: false
        type: boolean
      style: form
    entityFilter:
      description: Only list entities of the schema that are in range of the specified
        entities
      explode: true
      in: query
      name: entityFilter
      required: false
      schema:
        default: []
        items:
          type: string
        type: array
      style: form
    entityFilterDistance:
      description: Specifies the search distance if entityFilter is used
      explode: true
      in: query
      name: entityFilterDistance
      required: false
      schema:
        default: 1
        type: integer
      style: form
    entityId:
      description: ID of entity to access
      explode: false
      in: path
      name: entityId
      required: true
      schema:
        type: string
      style: simple
    schemaId:
      description: ID of schema to access
      explode: false
      in: path
      name: schemaId
      required: true
      schema:
        type: string
      style: simple
    attributeId:
      description: ID of attribute to access
      explode: false
      in: path
      name: attributeId
      required: true
      schema:
        type: string
      style: simple
    relationId:
      description: ID of relation to access
      explode: false
      in: path
      name: relationId
      required: true
      schema:
        type: string
      style: simple
  schemas:
    DataSource:
      example:
        plugin: plugin
        description: description
        id: id
        text_data:
        - input_field: input_field
          value: value
        - input_field: input_field
          value: value
        populated_input_fields:
        - populated_input_fields
        - populated_input_fields
      properties:
        id:
          title: id
          type: string
        description:
          title: description
          type: string
        plugin:
          title: plugin
          type: string
        populated_input_fields:
          items:
            type: string
          title: populated_input_fields
          type: array
        text_data:
          items:
            $ref: '#/components/schemas/DataSource_text_data_inner'
          title: text_data
          type: array
      required:
      - id
      - plugin
      title: DataSource
    EntityLink:
      format: url
      title: EntityLink
      type: string
    Format:
      example:
        inputs:
        - inputs
        - inputs
        name: name
      properties:
        name:
          title: name
          type: string
        inputs:
          items:
            type: string
          title: inputs
          type: array
      title: Format
    Partition:
      example:
        entities:
        - isObjectInRelation:
          - objectCardinality:
              cardinality: cardinality
            subjectCardinality:
              cardinality: cardinality
            hasSubjectEntity: ""
            relationName:
            - relationName
            - relationName
            hasObjectEntity: ""
            inverseRelation: inverseRelation
            hasAttribute:
            - attributeName:
              - attributeName
              - attributeName
              hasAttributeModifier:
              - attributeModifier: attributeModifier
              - attributeModifier: attributeModifier
            - attributeName:
              - attributeName
              - attributeName
              hasAttributeModifier:
              - attributeModifier: attributeModifier
              - attributeModifier: attributeModifier
            hasRelationModifier:
            - relationModifier: relationModifier
            - relationModifier: relationModifier
          - objectCardinality:
              cardinality: cardinality
            subjectCardinality:
              cardinality: cardinality
            hasSubjectEntity: ""
            relationName:
            - relationName
            - relationName
            hasObjectEntity: ""
            inverseRelation: inverseRelation
            hasAttribute:
            - attributeName:
              - attributeName
              - attributeName
              hasAttributeModifier:
              - attributeModifier: attributeModifier
              - attributeModifier: attributeModifier
            - attributeName:
              - attributeName
              - attributeName
              hasAttributeModifier:
              - attributeModifier: attributeModifier
              - attributeModifier: attributeModifier
            hasRelationModifier:
            - relationModifier: relationModifier
            - relationModifier: relationModifier
          hasEntityModifier:
          - entityModifier: entityModifier
          - entityModifier: entityModifier
          entityName:
          - entityName
          - entityName
          entityUrl: entityUrl
          hasAttribute:
          - attributeName:
            - attributeName
            - attributeName
            hasAttributeModifier:
            - attributeModifier: attributeModifier
            - attributeModifier: attributeModifier
          - attributeName:
            - attributeName
            - attributeName
            hasAttributeModifier:
            - attributeModifier: attributeModifier
            - attributeModifier: attributeModifier
          isSubjectInRelation:
          - objectCardinality:
              cardinality: cardinality
            subjectCardinality:
              cardinality: cardinality
            hasSubjectEntity: ""
            relationName:
            - relationName
            - relationName
            hasObjectEntity: ""
            inverseRelation: inverseRelation
            hasAttribute:
            - attributeName:
              - attributeName
              - attributeName
              hasAttributeModifier:
              - attributeModifier: attributeModifier
              - attributeModifier: attributeModifier
            - attributeName:
              - attributeName
              - attributeName
              hasAttributeModifier:
              - attributeModifier: attributeModifier
              - attributeModifier: attributeModifier
            hasRelationModifier:
            - relationModifier: relationModifier
            - relationModifier: relationModifier
          - objectCardinality:
              cardinality: cardinality
            subjectCardinality:
              cardinality: cardinality
            hasSubjectEntity: ""
            relationName:
            - relationName
            - relationName
            hasObjectEntity: ""
            inverseRelation: inverseRelation
            hasAttribute:
            - attributeName:
              - attributeName
              - attributeName
              hasAttributeModifier:
              - attributeModifier: attributeModifier
              - attributeModifier: attributeModifier
            - attributeName:
              - attributeName
              - attributeName
              hasAttributeModifier:
              - attributeModifier: attributeModifier
              - attributeModifier: attributeModifier
            hasRelationModifier:
            - relationModifier: relationModifier
            - relationModifier: relationModifier
        - isObjectInRelation:
          - objectCardinality:
              cardinality: cardinality
            subjectCardinality:
              cardinality: cardinality
            hasSubjectEntity: ""
            relationName:
            - relationName
            - relationName
            hasObjectEntity: ""
            inverseRelation: inverseRelation
            hasAttribute:
            - attributeName:
              - attributeName
              - attributeName
              hasAttributeModifier:
              - attributeModifier: attributeModifier
              - attributeModifier: attributeModifier
            - attributeName:
              - attributeName
              - attributeName
              hasAttributeModifier:
              - attributeModifier: attributeModifier
              - attributeModifier: attributeModifier
            hasRelationModifier:
            - relationModifier: relationModifier
            - relationModifier: relationModifier
          - objectCardinality:
              cardinality: cardinality
            subjectCardinality:
              cardinality: cardinality
            hasSubjectEntity: ""
            relationName:
            - relationName
            - relationName
            hasObjectEntity: ""
            inverseRelation: inverseRelation
            hasAttribute:
            - attributeName:
              - attributeName
              - attributeName
              hasAttributeModifier:
              - attributeModifier: attributeModifier
              - attributeModifier: attributeModifier
            - attributeName:
              - attributeName
              - attributeName
              hasAttributeModifier:
              - attributeModifier: attributeModifier
              - attributeModifier: attributeModifier
            hasRelationModifier:
            - relationModifier: relationModifier
            - relationModifier: relationModifier
          hasEntityModifier:
          - entityModifier: entityModifier
          - entityModifier: entityModifier
          entityName:
          - entityName
          - entityName
          entityUrl: entityUrl
          hasAttribute:
          - attributeName:
            - attributeName
            - attributeName
            hasAttributeModifier:
            - attributeModifier: attributeModifier
            - attributeModifier: attributeModifier
          - attributeName:
            - attributeName
            - attributeName
            hasAttributeModifier:
            - attributeModifier: attributeModifier
            - attributeModifier: attributeModifier
          isSubjectInRelation:
          - objectCardinality:
              cardinality: cardinality
            subjectCardinality:
              cardinality: cardinality
            hasSubjectEntity: ""
            relationName:
            - relationName
            - relationName
            hasObjectEntity: ""
            inverseRelation: inverseRelation
            hasAttribute:
            - attributeName:
              - attributeName
              - attributeName
              hasAttributeModifier:
              - attributeModifier: attributeModifier
              - attributeModifier: attributeModifier
            - attributeName:
              - attributeName
              - attributeName
              hasAttributeModifier:
              - attributeModifier: attributeModifier
              - attributeModifier: attributeModifier
            hasRelationModifier:
            - relationModifier: relationModifier
            - relationModifier: relationModifier
          - objectCardinality:
              cardinality: cardinality
            subjectCardinality:
              cardinality: cardinality
            hasSubjectEntity: ""
            relationName:
            - relationName
            - relationName
            hasObjectEntity: ""
            inverseRelation: inverseRelation
            hasAttribute:
            - attributeName:
              - attributeName
              - attributeName
              hasAttributeModifier:
              - attributeModifier: attributeModifier
              - attributeModifier: attributeModifier
            - attributeName:
              - attributeName
              - attributeName
              hasAttributeModifier:
              - attributeModifier: attributeModifier
              - attributeModifier: attributeModifier
            hasRelationModifier:
            - relationModifier: relationModifier
            - relationModifier: relationModifier
        title: title
      properties:
        title:
          title: title
          type: string
        entities:
          items:
            $ref: '#/components/schemas/Entity'
          title: entities
          type: array
      title: Partition
    Schema:
      example:
        schemaFile: schemaFile
        entities:
        - null
        - null
        implementation: implementation
        description: description
        id: id
        sourceFile: sourceFile
      properties:
        id:
          title: id
          type: string
        description:
          title: description
          type: string
        implementation:
          title: implementation
          type: string
        schemaFile:
          title: schemaFile
          type: string
        sourceFile:
          title: sourceFile
          type: string
        entities:
          items:
            $ref: '#/components/schemas/EntityLink'
          title: entities
          type: array
          xml:
            name: entities
      title: Schema
      xml:
        name: schema
    AttributeModifier:
      enum:
      - AttributeModifier: key
      example:
        attributeModifier: attributeModifier
      properties:
        attributeModifier:
          type: string
      required:
      - attributeModifier
      title: AttributeModifier
    Attribute:
      example:
        attributeName:
        - attributeName
        - attributeName
        hasAttributeModifier:
        - attributeModifier: attributeModifier
        - attributeModifier: attributeModifier
      properties:
        hasAttributeModifier:
          default: []
          items:
            $ref: '#/components/schemas/AttributeModifier'
          title: hasAttributeModifier
          type: array
        attributeName:
          items:
            type: string
          minItems: 1
          title: attributeName
          type: array
      required:
      - attributeName
      title: Attribute
    EntityModifier:
      enum:
      - EntityModifier: weak
      example:
        entityModifier: entityModifier
      properties:
        entityModifier:
          type: string
      required:
      - entityModifier
      title: EntityModifier
    RelationModifier:
      enum:
      - RelationModifier: identifying
      example:
        relationModifier: relationModifier
      properties:
        relationModifier:
          type: string
      required:
      - relationModifier
      title: RelationModifier
    Cardinality:
      enum:
      - Cardinality: oneOrNone
      - Cardinality: oneOrMore
      - Cardinality: any
      - Cardinality: exactlyOne
      example:
        cardinality: cardinality
      properties:
        cardinality:
          type: string
      required:
      - cardinality
      title: Cardinality
    Relation:
      example:
        objectCardinality:
          cardinality: cardinality
        subjectCardinality:
          cardinality: cardinality
        hasSubjectEntity: ""
        relationName:
        - relationName
        - relationName
        hasObjectEntity: ""
        inverseRelation: inverseRelation
        hasAttribute:
        - attributeName:
          - attributeName
          - attributeName
          hasAttributeModifier:
          - attributeModifier: attributeModifier
          - attributeModifier: attributeModifier
        - attributeName:
          - attributeName
          - attributeName
          hasAttributeModifier:
          - attributeModifier: attributeModifier
          - attributeModifier: attributeModifier
        hasRelationModifier:
        - relationModifier: relationModifier
        - relationModifier: relationModifier
      properties:
        hasAttribute:
          default: []
          items:
            $ref: '#/components/schemas/Attribute'
          title: hasAttribute
          type: array
        hasObjectEntity:
          title: hasObjectEntity
        hasRelationModifier:
          default: []
          items:
            $ref: '#/components/schemas/RelationModifier'
          title: hasRelationModifier
          type: array
        hasSubjectEntity:
          title: hasSubjectEntity
        inverseRelation:
          nullable: true
          title: inverseRelation
          type: string
        objectCardinality:
          $ref: '#/components/schemas/Cardinality'
        subjectCardinality:
          $ref: '#/components/schemas/Cardinality'
        relationName:
          items:
            type: string
          minItems: 1
          title: relationName
          type: array
      required:
      - hasObjectEntity
      - hasSubjectEntity
      - objectCardinality
      - relationName
      - subjectCardinality
      title: Relation
    Entity:
      example:
        isObjectInRelation:
        - objectCardinality:
            cardinality: cardinality
          subjectCardinality:
            cardinality: cardinality
          hasSubjectEntity: ""
          relationName:
          - relationName
          - relationName
          hasObjectEntity: ""
          inverseRelation: inverseRelation
          hasAttribute:
          - attributeName:
            - attributeName
            - attributeName
            hasAttributeModifier:
            - attributeModifier: attributeModifier
            - attributeModifier: attributeModifier
          - attributeName:
            - attributeName
            - attributeName
            hasAttributeModifier:
            - attributeModifier: attributeModifier
            - attributeModifier: attributeModifier
          hasRelationModifier:
          - relationModifier: relationModifier
          - relationModifier: relationModifier
        - objectCardinality:
            cardinality: cardinality
          subjectCardinality:
            cardinality: cardinality
          hasSubjectEntity: ""
          relationName:
          - relationName
          - relationName
          hasObjectEntity: ""
          inverseRelation: inverseRelation
          hasAttribute:
          - attributeName:
            - attributeName
            - attributeName
            hasAttributeModifier:
            - attributeModifier: attributeModifier
            - attributeModifier: attributeModifier
          - attributeName:
            - attributeName
            - attributeName
            hasAttributeModifier:
            - attributeModifier: attributeModifier
            - attributeModifier: attributeModifier
          hasRelationModifier:
          - relationModifier: relationModifier
          - relationModifier: relationModifier
        hasEntityModifier:
        - entityModifier: entityModifier
        - entityModifier: entityModifier
        entityName:
        - entityName
        - entityName
        entityUrl: entityUrl
        hasAttribute:
        - attributeName:
          - attributeName
          - attributeName
          hasAttributeModifier:
          - attributeModifier: attributeModifier
          - attributeModifier: attributeModifier
        - attributeName:
          - attributeName
          - attributeName
          hasAttributeModifier:
          - attributeModifier: attributeModifier
          - attributeModifier: attributeModifier
        isSubjectInRelation:
        - objectCardinality:
            cardinality: cardinality
          subjectCardinality:
            cardinality: cardinality
          hasSubjectEntity: ""
          relationName:
          - relationName
          - relationName
          hasObjectEntity: ""
          inverseRelation: inverseRelation
          hasAttribute:
          - attributeName:
            - attributeName
            - attributeName
            hasAttributeModifier:
            - attributeModifier: attributeModifier
            - attributeModifier: attributeModifier
          - attributeName:
            - attributeName
            - attributeName
            hasAttributeModifier:
            - attributeModifier: attributeModifier
            - attributeModifier: attributeModifier
          hasRelationModifier:
          - relationModifier: relationModifier
          - relationModifier: relationModifier
        - objectCardinality:
            cardinality: cardinality
          subjectCardinality:
            cardinality: cardinality
          hasSubjectEntity: ""
          relationName:
          - relationName
          - relationName
          hasObjectEntity: ""
          inverseRelation: inverseRelation
          hasAttribute:
          - attributeName:
            - attributeName
            - attributeName
            hasAttributeModifier:
            - attributeModifier: attributeModifier
            - attributeModifier: attributeModifier
          - attributeName:
            - attributeName
            - attributeName
            hasAttributeModifier:
            - attributeModifier: attributeModifier
            - attributeModifier: attributeModifier
          hasRelationModifier:
          - relationModifier: relationModifier
          - relationModifier: relationModifier
      properties:
        hasAttribute:
          default: []
          items:
            $ref: '#/components/schemas/Attribute'
          title: hasAttribute
          type: array
        hasEntityModifier:
          default: []
          items:
            $ref: '#/components/schemas/EntityModifier'
          title: hasEntityModifier
          type: array
        isObjectInRelation:
          default: []
          items:
            $ref: '#/components/schemas/Relation'
          title: isObjectInRelation
          type: array
        isSubjectInRelation:
          default: []
          items:
            $ref: '#/components/schemas/Relation'
          title: isSubjectInRelation
          type: array
        entityName:
          items:
            type: string
          minItems: 1
          title: entityName
          type: array
        entityUrl:
          nullable: true
          title: entityUrl
          type: string
      required:
      - entityName
      title: Entity
    DataSource_text_data_inner:
      example:
        input_field: input_field
        value: value
      properties:
        input_field:
          title: input_field
          type: string
        value:
          title: value
          type: string
      required:
      - input_field
      - value
      title: DataSource_text_data_inner
